version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  django:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 django_notipus.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/static
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    depends_on:
      - db
    networks:
      - app_network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local

networks:
  app_network:
    driver: bridge
